Blacklist MSVC `/permissive` and PCH compiler flags
These are MSVC flags that cause `clang-cl.exe` to crash, and are
unnecessary for cquery.

If the `/permissive` flag is present, it causes this error:

> clang-cl.exe: error: no such file or directory: '/permissive'

If any of the PCH flags are present, the following error occurs:

> error: input is not a PCH file